### ISSUE TITLE
Sourcemaps not working

### ISSUE THREAD

**Issue by quantuminformation** [pngwn/REPLicant#3]
The code runs fine but I'm not able to hit any debugger statements in source maps.

Some errors:

![image](https://user-images.githubusercontent.com/216566/101152745-cada6e00-3623-11eb-898f-cadfe7d93eb0.png)
![image](https://user-images.githubusercontent.com/216566/101152754-cf9f2200-3623-11eb-8335-b605d390a596.png)

**Comment by pngwn** [comment]
Not really sure. I'd be happy to look at any PRs to fix this but I won't be working on this project actively as it is more a demonstration than a production ready solution.
