### ISSUE TITLE
Access store in worker.js used in src

### ISSUE THREAD

**Issue by quantuminformation** [pngwn/REPLicant#5]
I tried this in the worker to see if it could share a store with the other src files in REPLicant
```js
import {  layoutStore } from "./stores/layoutStore";
console.log(get(configStore));
```
But the store is null when logging.

Is it possible to share data across to the compiled app from the REPLicant app?

**Comment by pngwn** [comment]
This wont work with workers, you need to pass messages around to sync state as demonstrated in the talk. You cannot have live 'in-memory' links across worker boundaries.
